name: Pipeline CI/CD BMW DevOps

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Construir imagen Docker
        run: docker build -t bmw-web .

      - name: Prueba basica - verificar imagen
        run: |
          docker run -d --name test-container -p 8080:80 bmw-web
          sleep 3
          curl -f http://localhost:8080 || exit 1
          echo "Prueba exitosa"
          docker stop test-container
          docker rm test-container

      - name: Desplegar en servidor AWS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~
            rm -rf proyecto-devops
            git clone https://github.com/R18pa/proyecto-devops.git
            cd proyecto-devops
            docker service rm bmw-web || true
            docker rmi bmw-web || true
            docker build -t bmw-web .
            docker service create --name bmw-web --publish 8080:80 bmw-web